###REGISTER A USER
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "Emanuel",
    "email": "marshcodes@gmail.com",
    "password":"pass",
    "phoneNumber":"+25470000000",
    "buildingId":"4be3a734-bc72-48fc-b6fa-612629c5046a"
}

###LOGIN A USER
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "marshcodes@gmail.com",
    "password":"pass"
}

###CHANGE PASSWORD
PUT http://localhost:3000/api/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5MzlhMzc1Zi05OTNiLTQ3NzYtOTlmNi00ZGM1MTcxMGY3NGQiLCJpYXQiOjE3MjM1NDk5MjEsImV4cCI6MTcyMzU1MzUyMX0.IBLXY0lpLVWwDqpPUGECBu5Lf78W9h36ZvCKFuymkLI

{
    "userId": "939a375f-993b-4776-99f6-4dc51710f74d",
    "oldPassword": "password",
    "newPassword":"12345678"
}

###GET USER BY ID
GET http://localhost:3000/api/auth/user/939a375f-993b-4776-99f6-4dc51710f74d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5MzlhMzc1Zi05OTNiLTQ3NzYtOTlmNi00ZGM1MTcxMGY3NGQiLCJpYXQiOjE3MjM1NDk5MjEsImV4cCI6MTcyMzU1MzUyMX0.IBLXY0lpLVWwDqpPUGECBu5Lf78W9h36ZvCKFuymkLI
