@baseUrl = http://localhost:3000/api/router
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmZDk0ZGQ1Ni1jYmIxLTRmZDItYjllMi05MWIyYTMzMjdlZjAiLCJpYXQiOjE3MjY1MDA4MDEsImV4cCI6MTcyNjUwNDQwMX0.d9FRCYeuZxiw2raIMK7FJqfVvGlsWL5cHrrekIc4QkA
### Add a new router
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "buildingId": "4be3a734-bc72-48fc-b6fa-612629c5046a",
  "name": "Router 1",
  "username": "admin",
  "password": "marshalsql"
}

### Update a router
PUT {{baseUrl}}/20cce841-06ee-4819-aeea-16c9f3e40d63
Content-Type: application/json

{
  "name": "Updated Router 1"
}

### Delete a router
DELETE {{baseUrl}}/20cce841-06ee-4819-aeea-16c9f3e40d63

### Get all routers
GET {{baseUrl}}

### Get router by id
GET {{baseUrl}}/20cce841-06ee-4819-aeea-16c9f3e40d63

### Get connected users for a router
GET {{baseUrl}}/20cce841-06ee-4819-aeea-16c9f3e40d63/connected-users