@baseUrl = http://localhost:3000/api/router
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5MzlhMzc1Zi05OTNiLTQ3NzYtOTlmNi00ZGM1MTcxMGY3NGQiLCJpYXQiOjE3MjQ0OTA4NzksImV4cCI6MTcyNDQ5NDQ3OX0.d3sGqmaV9-FfY1WMVD011wnQik8H9zeCV2t00brkVHw

### Add a new router
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "buildingId": "20cce841-06ee-4819-aeea-16c9f3e40d63",
  "name": "Router 1",
  "username": "admin",
  "password": "eaw111hh"
}

### Update a router
PUT {{baseUrl}}/20cce841-06ee-4819-aeea-16c9f3e40d63
Content-Type: application/json

{
  "name": "Updated Router 1"
}

### Delete a router
DELETE {{baseUrl}}/20cce841-06ee-4819-aeea-16c9f3e40d63

### Get all routers
GET {{baseUrl}}

### Get router by id
GET {{baseUrl}}/20cce841-06ee-4819-aeea-16c9f3e40d63

### Get connected users for a router
GET {{baseUrl}}/20cce841-06ee-4819-aeea-16c9f3e40d63/connected-users