### Initiate Payment and create subscription
POST http://localhost:3000/api/payment/initiate
Content-Type: application/json

{
  "planId": "e56b7245-859d-407f-b16f-197c57edd778",
  "userId": "939a375f-993b-4776-99f6-4dc51710f74d",
  "phoneNumber": "254112272250"
}
